"""empty message

Revision ID: 4f667664f672
Revises: 6d6fd56add74
Create Date: 2017-09-02 23:05:12.988828

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2 


# revision identifiers, used by Alembic.
revision = '4f667664f672'
down_revision = '6d6fd56add74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store_tag_rel',
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['store_tag.id'], )
    )
    op.drop_index('idx_store_location', table_name='store')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_store_location', 'store', ['location'], unique=False)
    op.drop_table('store_tag_rel')
    op.drop_table('store_tag')
    # ### end Alembic commands ###
